In [3]:
import pandas as pd
import numpy as np

# visualization
import matplotlib.pyplot as plt
import seaborn as sns

## Evaluation parameter for Linear regression
from sklearn.linear_model import LinearRegression,LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error,mean_squared_error,r2_score

## Evaluation parameter for Logistic regression
from sklearn.metrics import confusion_matrix,multilabel_confusion_matrix
from sklearn.metrics import classification_report,accuracy_score
from sklearn.metrics import roc_auc_score,roc_curve

In [4]:
df = pd.read_csv("iris.csv")
df

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm  \
0      1            5.1           3.5            1.4           0.2   
1      2            4.9           3.0            1.4           0.2   
2      3            4.7           3.2            1.3           0.2   
3      4            4.6           3.1            1.5           0.2   
4      5            5.0           3.6            1.4           0.2   
..   ...            ...           ...            ...           ...   
145  146            6.7           3.0            5.2           2.3   
146  147            6.3           2.5            5.0           1.9   
147  148            6.5           3.0            5.2           2.0   
148  149            6.2           3.4            5.4           2.3   
149  150            5.9           3.0            5.1           1.8   

            Species  
0       Iris-setosa  
1       Iris-setosa  
2       Iris-setosa  
3       Iris-setosa  
4       Iris-setosa  
..              ...  
145  Iris-virginica  
146  Iris-virginica  
147  Iris-virginica  
148  Iris-virginica  
149  Iris-virginica  

[150 rows x 6 columns]

In [30]:
# a = np.array(df.iloc[:, 0:5])
# a

array([[1.00e+00, 5.10e+00, 3.50e+00, 1.40e+00, 2.00e-01],
       [2.00e+00, 4.90e+00, 3.00e+00, 1.40e+00, 2.00e-01],
       [3.00e+00, 4.70e+00, 3.20e+00, 1.30e+00, 2.00e-01],
       [4.00e+00, 4.60e+00, 3.10e+00, 1.50e+00, 2.00e-01],
       [5.00e+00, 5.00e+00, 3.60e+00, 1.40e+00, 2.00e-01],
       [6.00e+00, 5.40e+00, 3.90e+00, 1.70e+00, 4.00e-01],
       [7.00e+00, 4.60e+00, 3.40e+00, 1.40e+00, 3.00e-01],
       [8.00e+00, 5.00e+00, 3.40e+00, 1.50e+00, 2.00e-01],
       [9.00e+00, 4.40e+00, 2.90e+00, 1.40e+00, 2.00e-01],
       [1.00e+01, 4.90e+00, 3.10e+00, 1.50e+00, 1.00e-01],
       [1.10e+01, 5.40e+00, 3.70e+00, 1.50e+00, 2.00e-01],
       [1.20e+01, 4.80e+00, 3.40e+00, 1.60e+00, 2.00e-01],
       [1.30e+01, 4.80e+00, 3.00e+00, 1.40e+00, 1.00e-01],
       [1.40e+01, 4.30e+00, 3.00e+00, 1.10e+00, 1.00e-01],
       [1.50e+01, 5.80e+00, 4.00e+00, 1.20e+00, 2.00e-01],
       [1.60e+01, 5.70e+00, 4.40e+00, 1.50e+00, 4.00e-01],
       [1.70e+01, 5.40e+00, 3.90e+00, 1.30e+00, 4.00e-01

In [31]:
# b = np.array(df.iloc[:, 5:])
# b

array([['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-setosa'],
       ['Iris-se

In [ ]:
df.drop("Id",axis=1,inplace=True)


In [69]:
df

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm          Species
0              5.1           3.5            1.4           0.2      Iris-setosa
1              4.9           3.0            1.4           0.2      Iris-setosa
2              4.7           3.2            1.3           0.2      Iris-setosa
3              4.6           3.1            1.5           0.2      Iris-setosa
4              5.0           3.6            1.4           0.2      Iris-setosa
..             ...           ...            ...           ...              ...
145            6.7           3.0            5.2           2.3  Iris-versicolor
146            6.3           2.5            5.0           1.9  Iris-versicolor
147            6.5           3.0            5.2           2.0  Iris-versicolor
148            6.2           3.4            5.4           2.3  Iris-versicolor
149            5.9           3.0            5.1           1.8  Iris-versicolor

[150 rows x 5 columns]

In [70]:
df["Species"].value_counts().to_dict()

{'Iris-versicolor': 100, 'Iris-setosa': 50}

In [71]:
df.replace({'Iris-virginica': 'Iris-versicolor'},inplace=True)

In [72]:
df["Species"].value_counts().to_dict()

{'Iris-versicolor': 100, 'Iris-setosa': 50}

In [ ]:
## Logistic Regression

In [73]:
x = df.drop("Species",axis =1)
y = df["Species"]

In [74]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size= 0.20,random_state=2,stratify=y)

In [75]:
y_train[0:5]

137    Iris-versicolor
46         Iris-setosa
111    Iris-versicolor
12         Iris-setosa
91     Iris-versicolor
Name: Species, dtype: object

In [76]:
y_test[0:5]

45         Iris-setosa
112    Iris-versicolor
149    Iris-versicolor
43         Iris-setosa
7          Iris-setosa
Name: Species, dtype: object

In [77]:
lr_clf = LogisticRegression()
lr_clf.fit(x_train,y_train)

LogisticRegression()

In [78]:
y_pred = lr_clf.predict(x_test)
y_pred[0:5]

array(['Iris-setosa', 'Iris-versicolor', 'Iris-versicolor', 'Iris-setosa',
       'Iris-setosa'], dtype=object)

In [79]:
acc_score = accuracy_score(y_test,y_pred)
acc_score

1.0

In [80]:
cnf_matrix = confusion_matrix(y_test,y_pred)
cnf_matrix

array([[10,  0],
       [ 0, 20]], dtype=int64)

In [81]:
clf_report = classification_report(y_test,y_pred)
print("Classification Repoer is:\n",clf_report )

Classification Repoer is:
                  precision    recall  f1-score   support

    Iris-setosa       1.00      1.00      1.00        10
Iris-versicolor       1.00      1.00      1.00        20

       accuracy                           1.00        30
      macro avg       1.00      1.00      1.00        30
   weighted avg       1.00      1.00      1.00        30



In [62]:
clf_probability = lr_clf.predict_proba(x_test)
clf_probability

array([[9.88303465e-01, 1.16965351e-02],
       [0.00000000e+00, 1.00000000e+00],
       [0.00000000e+00, 1.00000000e+00],
       [9.96872667e-01, 3.12733304e-03],
       [1.00000000e+00, 2.94848352e-15],
       [1.00000000e+00, 1.81988433e-10],
       [1.00000000e+00, 1.56455978e-12],
       [9.99755575e-01, 2.44424600e-04],
       [4.80053890e-07, 9.99999520e-01],
       [0.00000000e+00, 1.00000000e+00],
       [1.73262335e-04, 9.99826738e-01],
       [2.17222462e-10, 1.00000000e+00],
       [4.78925144e-09, 9.99999995e-01],
       [5.35593792e-12, 1.00000000e+00],
       [0.00000000e+00, 1.00000000e+00],
       [0.00000000e+00, 1.00000000e+00],
       [0.00000000e+00, 1.00000000e+00],
       [2.58475967e-04, 9.99741524e-01],
       [0.00000000e+00, 1.00000000e+00],
       [2.22044605e-15, 1.00000000e+00],
       [0.00000000e+00, 1.00000000e+00],
       [1.00000000e+00, 6.29993065e-14],
       [7.97730985e-01, 2.02269015e-01],
       [1.00000000e+00, 5.25011598e-15],
       [2.681980

In [82]:
clf_probability[:,1]

array([1.16965351e-02, 1.00000000e+00, 1.00000000e+00, 3.12733304e-03,
       2.94848352e-15, 1.81988433e-10, 1.56455978e-12, 2.44424600e-04,
       9.99999520e-01, 1.00000000e+00, 9.99826738e-01, 1.00000000e+00,
       9.99999995e-01, 1.00000000e+00, 1.00000000e+00, 1.00000000e+00,
       1.00000000e+00, 9.99741524e-01, 1.00000000e+00, 1.00000000e+00,
       1.00000000e+00, 6.29993065e-14, 2.02269015e-01, 5.25011598e-15,
       9.99731802e-01, 1.00000000e+00, 1.00000000e+00, 1.00000000e+00,
       1.00000000e+00, 1.82517290e-11])

#### fpr,tpr,threshold = roc_curve(y_test,clf_probability[:,1])

In [83]:
x.head(1).T

0
SepalLengthCm  5.1
SepalWidthCm   3.5
PetalLengthCm  1.4
PetalWidthCm   0.2

In [87]:
SepalLengthCm = 5.1
SepalWidthCm = 3.5
PetalLengthCm = 1.4
PetalWidthCm = 0.2

In [84]:
column_names = x.columns
column_names

Index(['SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm'], dtype='object')

In [85]:
test_array = np.zeros(len(x.columns))
test_array

array([0., 0., 0., 0.])

In [88]:
test_array[0] = SepalLengthCm
test_array[1] = SepalWidthCm
test_array[2] = PetalLengthCm
test_array[3] = PetalWidthCm

In [89]:
test_array

array([5.1, 3.5, 1.4, 0.2])

In [91]:
lr_clf.predict([test_array])

C:\Users\hp\AppData\Local\Programs\Python\Python39\lib\site-packages\sklearn\base.py:450: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(


array(['Iris-setosa'], dtype=object)

In [ ]:
## create Model(lr_clf) pickle file

In [92]:
import pickle

with open("Linear_Model.pkl","wb") as f:
    pickle.dump(lr_clf,f)

In [95]:
project_data = {"columns":list(x.columns)}
project_data

{'columns': ['SepalLengthCm', 'SepalWidthCm', 'PetalLengthCm', 'PetalWidthCm']}

In [96]:
import json

with open("Project_data.json","w") as f:
    json.dump(project_data,f)